// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukhwlqpmkrdkqvhenxnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVraHdscXBta3Jka3F2aGVueG5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NTY5NDQsImV4cCI6MjA2MDUzMjk0NH0.2rvBlP3JLpdoi53AC-RTiLIRfLDe-6mZ05k14a5Bjio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
